### ISSUE TITLE
Ajustar o comando de instalação no README

### ISSUE THREAD

**Issue by fmsouza** [vitoralvesdev/react-native-componentes#25]
Quando você instala o pacote com a flag `--save-dev` você está salvando na seção `devDependencies` do seu `package.json`. Isso quer dizer que essa lib pode ser desconsiderada na hora de gerar um build de produção, o que pode gerar bugs nas instalações em outros projetos.

O correto nesse caso seria `npm install --save react-native-components`.

**Comment by vitoralvesdev** [comment]
@fmsouza Muito obrigado pela observação, correção feita.
